### ISSUE TITLE
instance not found

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#529]
Hi Leo,

Can you explain why type class resolution fails? It succeeds when I replace the last line by `@id _ x`. What is the difference between `id x` and `@id _ x`?

``` lean
structure diagram [class] :=
  (ob : Type₁)

open diagram

definition id [D : diagram] (x : ob) : ob := x

definition my_instance [instance] (X : Type₁) : diagram := diagram.mk X

definition foo (X : Type₁) (x : X) : X :=
id x
```

**Comment by leodemoura** [comment]
The type class resolution fails because it couldn't instantiate `X`. 
We reject solutions that contains meta-variables. We say they are not complete solutions.
This kind of solutions generated a lot of problems in the past.
They are rejected here:
https://github.com/leanprover/lean/blob/master/src/library/tactic/class_instance_synth.cpp#L382
If we replace line 382 with `return true;`, then the example is accepted.

When we use `@id _ x`, we are telling Lean we want to provide the instances manually and/or solving unification constraints. If we use

``` lean
set_option pp.implicit true
print definition foo
```

We see the following term was produced `@id (mk X) x`.

**Comment by fpvandoorn** [comment]
I understand why it fails. That is reasonable in retrospect. 
How interesting (and weird) that it can find the instance `mk X` without `mk` being an instance. But succeeding "too often" is not a problem, that's good :-)

How about the following example? Would it be possible to support that? Since `X` is fixed in the context, there should be no metavariable after trying the instance `my_instance`, right?

``` lean
structure diagram [class] :=
  (ob : Type₁)

open diagram

definition id [D : diagram] (x : ob) : ob := x

context
parameters (X : Type₁)

definition my_instance [instance] : diagram := diagram.mk X

definition foo (x : X) : X :=
id x

end
```

I am doing something strange here, namely having a class without arguments, so I don't care too much if this isn't supported.

---

Background information: 
The reason I'm pushing this a bit is to use the `diagram` structure when defining the colimit:

``` lean
structure diagram [class] :=
  (Iob : Type)
  (Ihom : Type)
  (ob : Iob → Type)
  (dom cod : Ihom → Iob)
  (hom : Π(j : Ihom), ob (dom j) → ob (cod j))
```

I could move some fields to the arguments: however, in general the context will provide too little information to figure out these arguments. For example in the context

``` lean
universe u
parameters {TL BL TR : Type.{u}} (f : TL → BL) (g : TL → TR)
```

I define

``` lean
  definition pushout_diag [reducible] : diagram :=
  diagram.mk pushout_ob
             bool
             (λi, pushout_ob.rec_on i TL BL TR)
             (λj, bool.rec_on j tl tl)
             (λj, bool.rec_on j bl tr)
             (λj, bool.rec_on j f  g)
```

and I want this instance to be found for metavariable `?D` if the only usable information from the context is that

``` lean
diagram.ob ?D ?x =?= BL
```

(This is the case if I write `definition inl (x : BL) : pushout := @inclusion _ _ x` where `inclusion : Π [D : diagram] {i : Iob}, ob i → colimit D`)

The reason why I hope type class inference still succeeds is because I will only ever have 1 instance of `diagram` in my context. An instance is just needed to define a special case of the general colimit, and after defining it, we will never need the instance again.

**Comment by leodemoura** [comment]
> How interesting (and weird) that it can find the instance mk X without mk being an instance. But succeeding "too often" is not a problem, that's good :-)

This is a side-effect of a "feature" used in the unifier.
I used double quotes because it is produces unexpected behavior like the one you observed, and it increases the search space for very little gain.
When we have a constraint of the form `M_1 =?= C.rec ... (?M_2 ...) ...`, where the left hand side is stuck because `?M_2 ...` is the main premise of `C.rec`, if `?M2` was not assigned by other constraints, the unifier will create a case-split where each case tries a different constructor of `C`.

**Comment by leodemoura** [comment]
> The reason why I hope type class inference still succeeds is because I will only ever have 1 instance of diagram in my context. An instance is just needed to define a special case of the general colimit, and after defining it, we will never need the instance again.

Perhaps we need a different mechanism. At least, we need some extra annotation.
I think we improved the type class resolution after we started to discard solutions that contained meta-variables. I think accepting that again would generate problems. If the meta-variables cannot be instantiated, it is super confusing for the user.

We have the `[multiple-instances]` annotation that instructs the type class resolution procedure to case-split on the different instances that can be generated.
We can add a `[partial-instances]` to indicate we will tolerate partial instances for a given class.
What do you think?

**Comment by fpvandoorn** [comment]
> We can add a [partial-instances] to indicate we will tolerate partial instances for a given class.
> What do you think?

That might be a good idea. This is a different case than the "normal" type class inference. However, I don't know how often this will come up.

But I'm still confused why my second example fails (the first code block in [my previous comment](https://github.com/leanprover/lean/issues/529#issuecomment-89714533)). Within the context, the parameter `X` is fixed, so why is there a metavariable after trying `my_instance`? Does type class inference "know" we are still in the context where `X` is fixed?

**Comment by leodemoura** [comment]
> Within the context, the parameter X is fixed, so why is there a metavariable after trying my_instance?
> Does type class inference "know" we are still in the context where X is fixed?

The `X` is not fixed for type class resolution.
The instance `my_instance` is the same inside and outside of the context.
In both cases, we need `X`. 
To have the behavior you want, we would have to add a notion of local instance that vanishes in the end of the context.

**Comment by fpvandoorn** [comment]
> To have the behavior you want, we would have to add a notion of local instance that vanishes in the end of the context.

I think that would be useful. It was the behavior I was expecting, since parameters are fixed in the context.

**Comment by fpvandoorn** [comment]
Note: there are two open "issues" in this issue: A new attribute `[partial-instances]` and "adding a notion of local instance in a context". While both could be useful at some point, I don't see a immediate use for either (I stopped using the `diagram` structure), so I think we can postpone this until we actually see a use for it.

**Comment by leodemoura** [comment]
Great. I was struggling with this one today too.
It turns out that the "local instances" are more complicated that I expected.
The current table of global instances is just a bunch of names and not arbitrary expressions.
